development:
  adapter: postgresql

test:
  adapter: postgresql

production:
  adapter: postgresql
  # url: redis://redistogo:eecbdb3c7ac5d99062c427913e724b76@dory.redistogo.com:11649/
  channel_prefix: typing_royale_backend_production
