development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: redis://redistogo:5f1667d89dd8e4167fe34dbe3907bde9@dory.redistogo.com:11649/
  channel_prefix: typing_royale_backend_production
